import Head from 'next/head';
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import { placeHolder } from "../placeholer";
import Slider from '../component/Slider/Slider';


export default function Home() {

  const sliderData = placeHolder[1]; 

  return (
    <div className={styles.container}>
      <Head>
        <title>Zephayar Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={
        {
          display: "flex",
          alignItems: 'center',
          justifyContent: "center",
          width: "100%", maxWidth: "70%",
          margin: "auto"
        }
      }>
        <Slider sliderData={sliderData} />
      </div>
    </div>
  )
}


export async function getServerSideProps(context) {

  return {
    props: {
      data: {}
    }
  }
}