import React, { useState, useEffect } from "react";
import { ThemeProvider } from "styled-components";
import { GlobalStyles } from "../pages/components/globalStyles";
import { lightTheme, darkTheme } from "../pages/ThemeConfig";
import Footer from "../pages/components/footer.js";
import Cards from "./components/card.js";
import { cardInfo } from "../pages/api/image";




const Home = () => {
  const [theme, setTheme] = useState('light');
  useEffect(() => {
    setTheme()
  }, []);
  const themeToggler = () => {
    theme === 'light' ? setTheme('dark') : setTheme('light')
  }

  return (
    <ThemeProvider theme={theme === 'light' ? lightTheme : darkTheme}>
      <div>
        <GlobalStyles />
        <div>
          <button onClick={themeToggler}>{theme == 'light' ? "Switch to Dark Theme" : "Switch to Light Theme"}</button>

        </div>

        <Cards cardInfo={cardInfo} />

      </div>

      <Footer />
    </ThemeProvider >


  );
};
export default Home;



// import Head from 'next/head';
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import Footer from "../pages/components/footer.js";
// import Cards from "./components/card.js";
// import { cardInfo } from "../pages/api/image";

// export default function Home() {

//   return (
//     <div className={styles.container}>
//       {/* <Head>
//         <title>Zephar Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head> */}

//       <main className={styles.main}>
//         <h1></h1>
//         <Cards />
//       </main>
//       <div className={styles.footer}>
//         <Footer />
//       </div>
//       <div className={styles.name}>
//         <p>Copyright 2022</p>

//       </div>

//     </div>

//   )
// }
